# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Demo website
email: prateek007.purohit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is a basic site created using jeykll and deployed by github as you can see in the url...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: -
github_username:  prateek21032000

# Build settings
markdown: kramdown
